version: 2
jobs:
  build71:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      BINTRAY_REPO: php71custom
      PACKAGE_VCS_URL: https://github.com/aursu/rpmbuild-php-memcached
    steps:
      - checkout
      - run:
          name: Git submodules sync
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Pull images for RPM build docker services
          command: docker-compose -f rpmbuild/docker-compose.bintray.yml pull
      - run:
          name: Build Docker images
          command: docker-compose build --no-cache --pull
      - run:
          name: Build RPM packages
          command: docker-compose up
      - run:
          name: Upload RPM packages into Bintray
          command: |
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos7bintray
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos8bintray
  build73:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      BINTRAY_REPO: php73custom
      PACKAGE_VCS_URL: https://github.com/aursu/rpmbuild-php-memcached
    steps:
      - checkout
      - run:
          name: Git submodules sync
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Pull images for RPM build docker services
          command: docker-compose -f rpmbuild/docker-compose.bintray.yml pull
      - run:
          name: Build Docker images (PHP 7.3)
          command: docker-compose -f docker-compose.php73.yml build --no-cache --pull
      - run:
          name: Build RPM packages (PHP 7.3)
          command: docker-compose -f docker-compose.php73.yml up
      - run:
          name: Upload RPM packages into Bintray
          command: |
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos7bintray
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos8bintray

workflows:
  version: 2
  memcachedbuild:
    jobs:
      - build73
      - build71